import type { Metadata } from "next";
import "./globals.css";
import { arimo, bungee, libre, notosan, sriracha } from "@/app/font";
import Header from "@/app/components/layout/Header";
import Footer from "@/app/components/layout/Footer";

export const metadata: Metadata = {
  title: "Coco Garden",
  description: "Generated by create next app",
  icons: {
    other: [
      {rel: 'icon', type: 'image', url: '/icon-coconut.jpg'}
    ]
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`
          ${arimo.variable} 
          ${bungee.variable} 
          ${libre.variable} 
          ${sriracha.variable} 
          ${notosan.variable} 
          antialiased
          flex 
          flex-col 
          min-h-screen
          `}
      >
        <Header></Header>
        <main className="flex-1 relative pt-[98px]">
          {children}
        </main>
        <Footer></Footer>
      </body>
    </html>
  );
}
